config/routes.rb
Apidoc::Application.routes.draw do
  get "pages/content"

  get "pages/examples"

  get "pages/downloads"

  get "pages/sdk"

  get "pages/orglist"

  match 'content/:resource' => 'pages#content', :as => 'content'
  match 'examples/:resource/:example' => 'pages#examples', :as => 'examples'
  match 'sdk/:type' => 'pages#sdk', :as => 'sdk'
  
  root :to => 'pages#content'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate
  
  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == "smetrics" && password == "apihelp"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def content
    if params[:resource].nil? then resource = 'introduction' else resource = params[:resource] end
    resource_params = GLOBAL['resources'][resource]
    #set the name param
    @resource = resource
    #set other params
    @content_path = "#{Rails.root.to_s}#{GLOBAL['content_path']}#{resource}" #not DRY, repeating Rails root in the path - figure out how to put this in the yml file itself
    #title
    @title = resource_params['title']
    #subhead
    @subhead = resource_params['subhead']
    #components
    @overview = resource_params['overview']
    @request = resource_params['request']
    @result = resource_params['result']
    @connections = resource_params['connections']
    #examples
    @examples = resource_params['examples']
    #disqus
    @disqus_identifier = "content/#{@resource}"
    @disqus_title = "API | Content | #{@title}"
  end

  def examples
    if params[:resource].nil? then resource = 'introduction' else resource = params[:resource] end
    if params[:example].nil? then @example = 1 else @example = params[:example].to_i end
    resource_params = GLOBAL['resources'][resource]
    #set the name param
    @resource = resource
    @content_path = "#{Rails.root.to_s}#{GLOBAL['content_path']}#{resource}" #not DRY, repeating Rails root in the path - figure out how to put this in the yml file itself
    #title
    @title = resource_params['title']
    #subhead
    @subhead = resource_params['subhead']
    #override
    if resource=='introduction' then
      @title = 'General'
      @subhead = ''
    end
    #examples
    @examples = resource_params['examples']
    #example title
    @example_title = resource_params['examples'][@example-1]
    #disqus
    @disqus_identifier = "examples/#{@resource}/#{@example}"
    @disqus_title = "API | Examples | #{@title} | #{@example_title}"
  end

  def downloads
  end

  def sdk
    if params[:type].nil? then @type = 'js' else @type = params[:type] end
    render :template => "pages/#{@type}_sdk"
  end

  def orglist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>NSF API Documentation</title>
	<meta name="description" content="">
	<meta name="author" content="">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
</head>
<body data-offset="50" data-target=".scrollspy" data-spy="scroll">
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">NSF API</a>
			<div class="nav-collapse">
				<ul id="mainnav" class="nav">
					<% GLOBAL['resources'].each do |resource,params| %>					
						<li<%= controller_name=='pages' && action_name=='content' && @resource == resource ? raw(' class="active"'): '' %>><%= link_to params['title'], content_path(resource) %></li>
					<% end %>
					<li<%= controller_name=='pages' && action_name == 'examples' ? raw(' class="active"'): '' %>><%= link_to "Examples", examples_path('introduction',1) %></li>
				</ul>
				<ul class="nav pull-right">
					<li class="dropdown" id="menu1">
						<a href="#menu1" class="dropdown-toggle" data-toggle="dropdown">Tools &amp; Resources <b class="caret"></b> </a>
						<ul class="dropdown-menu">
							<li><%= link_to "Downloads", pages_downloads_path %></li>
							<li><%= link_to "SDK", sdk_path('js') %></li>
							<li><%= link_to "Organization List", pages_orglist_path %></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<div class="container" id="main" role="main">
	<%= yield %>
</div>

<script type"text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'apidoc'; // required: replace example with your forum shortname
var disqus_identifier = "<%=@disqus_identifier%>";
var disqus_title = "<%=@disqus_title%>";

/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
    var dsq = document.createElement('script');
	dsq.type = 'text/javascript';
	dsq.async = true;
    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();

(function () {
    var s = document.createElement('script'); 
	s.async = true;
    s.type = 'text/javascript';
    s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());		
</script>
</body>
</html>

app/views/pages/content.html.erb
<div class="row">
	<div class="span9">
		<div id="header" class="page-header">
		    <h1><%=@title%></h1>
			<p class="lead"><%=@subhead%></p>
		</div>
		<% if @overview then %>
		<div class="section" id="overview">
		<h2><%=@overview['title']?@overview['title']:'Overview'%> <small><%=@overview['subhead']%></small></h2>
		<div>
		<%=render :file=>"#{@content_path}/overview.html"%>
		</div>
		</div>
		<% end %>
		<% if @request then %>
		<div class="section" id="request">
		<h2><%=@request['title']?@request['title']:'Request'%> <small><%=@request['subhead']?@request['subhead']:'Search for user information using the GET Method.'%></small></h2>
		<div>
		<%=render :file=>"#{@content_path}/request.html"%>
		</div>
		</div>
		<% end %>
		<% if @result then %>
		<div class="section" id="result">
		<h2><%=@result['title']?@result['title']:'Result'%> <small><%=@result['subhead']?@result['subhead']:'Properties (meta data)'%></small></h2>
		<div>
		<%=render :file=>"#{@content_path}/result.html"%>
		</div>
		</div>
		<% end %>
		<% if @connections then %>
		<div class="section" id="connections">
		<h2><%=@connections['title']?@connections['title']:'Connections'%> <small><%=@connections['subhead']?@connections['subhead']:'(linkages)'%></small></h2>
		<div>
		<%=render :file=>"#{@content_path}/connections.html"%>
		</div>
		</div>
		<% end %>
		<div class="section">
			<h2>Comments and Feedback <small>Share your thoughts on the API, ask questions, learn from others. Join the discussion below.</small></h2>
			<div id="disqus_thread"></div>
	        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
	     </div>	
 	</div> <!-- span9 -->
	<div class="span3">
		<div class="well sidebarnav fixed-right scrollspy">
			<ul class="nav nav-list">
				<li class="nav-header">Jump To:</li>
			   	<% if @overview then %><li><a href="#overview"><i class="icon-search"></i> Overview</a></li><% end %>
			   	<% if @request then %><li><a href="#request"><i class="icon-cog"></i> Request</a></li><% end %>
			   	<% if @result then %><li><a href="#result"><i class="icon-th-list"></i> Result</a></li><% end %>
			   	<% if @connections then %><li><a href="#connections"><i class="icon-resize-horizontal"></i> Connections</a></li><% end %>
				<li class="divider"></li>
				<li><h4>Comments? Feedback?</h4><p>Tell us what you think.</p> <a href="#disqus_thread" data-disqus-identifier="<%=@disqus_identifier%>"></a></li>
			</ul>
			<% if (@examples) then %>
			<hr />
			<div class="examples">
			<h4>Examples</h4>
			<ol>
				<% @examples.each_with_index do |example, index| %>
				<li><%=link_to "#{example}", examples_path(@resource,index+1) %><small><a href="#disqus_thread" data-disqus-identifier="examples/<%=@resource%>/<%=(index+1)%>"></a></small></li>
				<% end %>
			</ol>
			<% end %>
		</div>		
	</div> <!-- span3 -->
</div>

app/views/pages/downloads.html.erb
<div id="header" class="page-header">
    <h2>Downloads</h1>
	<p class="lead">PDF and Word versions of the documentation</p>
</div>
<p>Here, put links to downloads of docs in pdf and word format</p>

app/views/pages/examples.html.erb
<div class="subnav">
	<ul class="nav nav-pills">
		<% GLOBAL['resources'].each do |resource, params| %>
			<% if params['examples'] then %>
			<li<%= @resource == resource ? raw(' class="active"'): '' %>><%=link_to resource=='introduction'?'General':params['title'], examples_path(resource,1) %></li>
			<% end %>
		<% end %>
	</ul>
</div>
<div class="row">
	<div class="span9">
		<div id="header" class="page-header">
		  <h1>Examples</h1>
		  <p class="lead">See the API in action! Browse the list of examples below.</p>
		</div>
		<div class="section">
		<h2><%=@title%> <small><%=@subhead%></small></h2>
		<div class="example">
		<h3>Example <%=@example%> <small><%=@example_title%></small></h3>
		<div class="alert"><strong>Feedback? Comments?</strong> Share your thoughts and join the discussion about this example. <span class="pull-right"><a href="#disqus_thread" data-disqus-identifier="<%=@disqus_identifier%>"></a></span></div>
		<%=render :file=>"#{@content_path}/examples_#{@example}.html"%>
		</div>
		</div>
		<div class="section">
			<h2>Comments and Feedback <small>Share your thoughts on the API, ask questions, learn from others. Join the discussion below.</small></h2>
			<div id="disqus_thread"></div>
	        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
	     </div>	
 	</div> <!-- span9 -->
	<div class="span3">
		<div class="well sidebarnav fixed-right examples">
			<h3>Examples</h3>
			<ol>
				<% @examples.each_with_index do |example, index| %>
				<li<%= @example == index+1 ? raw(' class="active"'): '' %>><%=link_to "#{example}", examples_path(@resource,index+1) %><small><a href="#disqus_thread" data-disqus-identifier="examples/<%=@resource%>/<%=(index+1)%>"></a></small></li>
				<% end %>
			</ol>
		</div>
 	</div> <!-- span3 -->	
</div>

app/views/pages/js_sdk.html.erb
<div class="subnav">
	<ul class="nav nav-pills">
		<li<%= @type == 'js' ? raw(' class="active"'): '' %>><%=link_to 'JavaScript', sdk_path('js') %></li>
		<li<%= @type == 'python' ? raw(' class="active"'): '' %>><%=link_to 'Python', sdk_path('python') %></li>
	</ul>
</div>
<div id="header" class="page-header">
    <h2>JavaScript SDK (Alpha)</h1>
	<p class="lead">A software development kit to include in your JavaScript projects.</p>
</div>
<div class="section">
<h2>How To Use</h2>
<p><a href="https://github.com/krishenn/sdk" target="_blank">Download the script file</a> and place it in your project directory.</p>
<p>Include it in your project as follows:</p>
<code>&lt;script src="pathtofile/sm.js" type="text/javascript" /&gt;</code>
</div>
<div class="section">
<h2>JavaScript SDK Usage</h2>
<form class="well form-horizontal">
	<div class="control-group">
		<label class="control-label"><strong>Show:</strong></label>
		<div class="controls">
			<select id="resource">
				<option value="">Select One</option>
				<option value="topics">List of Topics</option>
				<option value="programs">List of Programs</option>
				<option value="divisions">List of Divisions</option>
				<option value="proposals">List of Proposals</option>
				<option value="institutions">List of Institutions</option>
				<option value="researchers">List of Researchers</option>
				<option value="">----</option>
				<option value="proposal">Proposal Details</option>
				<option value="institution">Institution Details</option>
				<option value="researcher">Researcher Details</option>
			</select>
		    <p class="help-block">Select an option above. The SDK call and the call results will be displayed below.</p>
		</div>
       </div>
</form>
<h2>Call</h2>
<pre id="call"></pre>
<h2>Result</h2>
<pre id="result"></pre>
</div>

<script type="text/javascript">
LoadView = Backbone.View.extend({
	events: {
		"change select#resource": "load",
	},
	load: function(e) {
		if (e) e.preventDefault();
		$('#result', this.el).html('Loading...');
		var resource = $('#resource').val();
		var options;
		if (resource=='topics') {
			options = {org:'CMMI',year:'2007-2009'};
			sm.topics(options,this.render);
		} else if (resource=='programs') {
			options = {org:'CMMI',year:'2007-2009'};
			sm.programs(options,this.render);						
		} else if (resource=='divisions') {
			options = {t:'551',year:'2007-2009'};
			sm.divisions(options,this.render);
		} else if (resource=='proposals') {
			options = {org:'CMMI',year:'2007-2009'};
			sm.proposals(options,this.render);						
		} else if (resource=='institutions') {
			options = {org:'CMMI',year:'2007-2009'};
			sm.institutions(options,this.render);						
		} else if (resource=='researchers') {
			options = {org:'CMMI',year:'2007-2009'};
			sm.researchers(options,this.render);						
		} else if (resource=='proposal') {
			options = '1126899';
			sm.proposal(options,this.render);						
		} else if (resource=='institution') {
			options = '0038950000';
			sm.institution(options,this.render);						
		} else if (resource=='researcher') {
			options = '269729592';
			sm.researcher(options,this.render);
		}
		if (typeof(options)!=='string') options = JSON.stringify(options);
		$('#call', this.el).html("sm."+resource+"("+options+",callback);");		
	},
	render: function(result) {
		if (result) result = jsl.format.formatJson(JSON.stringify(result));
		else result = '<div class="alert"><strong>Error</strong>: You must be connected to the NSF network to access the API.</div>';
		$('#result', this.el).html(result);
	}	
});
$(function(){
	var view = new LoadView({el:$('#main')});
});
</script>

app/views/pages/orglist.html.erb
<div id="header" class="page-header">
    <h1>Organization List</h1>
	<p class="lead">Codes for org for topic object.</p>
</div>
<table class="table table-bordered">
  <thead>
	<tr>
      <th>Title</th>
      <th>Direct</th>
      <th>Division</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Office of the Director </td>
      <td>OD</td>
      <td> </td>
      <td>OD,OCI,OGC,OIA,EPSCoR,OISE,ODI,OLPA,OPP</td>
    </tr>
    <tr>
      <td>Office of Cyberinfrastructure</td>
      <td>OD</td>
      <td>OCI</td>
      <td>OCI</td>
    </tr>
    <tr>
      <td>Office of the General Counsel</td>
      <td>OD</td>
      <td>OGC</td>
      <td>OGC</td>
    </tr>
    <tr>
      <td>Office of Integrative Activities</td>
      <td>OD</td>
      <td>OIA</td>
      <td>OIA,EPSCoR</td>
    </tr>
    <tr>
      <td valign="bottom">
        <p>Office of Experimental Program To Stimulate Competitive </p>
        <p>Research</p>
      </td>
      <td>OIA</td>
      <td>EPSCoR</td>
      <td>EPSCoR</td>
    </tr>
    <tr>
      <td>Office of International Science and Engineering</td>
      <td>OD</td>
      <td>OISE</td>
      <td>OISE</td>
    </tr>
    <tr>
      <td>Office of Diversity and Inclusion (ODI)</td>
      <td>OD</td>
      <td>ODI</td>
      <td>ODI</td>
    </tr>
    <tr>
      <td>Office of Legislative &amp; Public Affairs</td>
      <td>OD</td>
      <td>OLPA</td>
      <td>OLPA</td>
    </tr>
    <tr>
      <td>Office of Polar Programs</td>
      <td>OD</td>
      <td>OPP</td>
      <td>OPP</td>
    </tr>
    <tr>
      <td>National Science Board </td>
      <td>NSB</td>
      <td> </td>
      <td>NSB</td>
    </tr>
    <tr>
      <td>Office of the Inspector General </td>
      <td>OIG</td>
      <td> </td>
      <td>OIG</td>
    </tr>
    <tr>
      <td>Directorate for Biological Sciences </td>
      <td>BIO</td>
      <td>OAD</td>
      <td>BIO,MCB,DBI,IOS,DEB,EF</td>
    </tr>
    <tr>
      <td>Division of Molecular &amp; Cellular Biosciences</td>
      <td>BIO</td>
      <td>MCB</td>
      <td>MCB</td>
    </tr>
    <tr>
      <td>Division of Biological Infrastructure</td>
      <td>BIO</td>
      <td>DBI</td>
      <td>DBI</td>
    </tr>
    <tr>
      <td>Division of Integrative Organismal Systems</td>
      <td>BIO</td>
      <td>IOS</td>
      <td>IOS</td>
    </tr>
    <tr>
      <td>Division of Environmental Biology</td>
      <td>BIO</td>
      <td>DEB</td>
      <td>DEB</td>
    </tr>
    <tr>
      <td>Emerging Frontiers Office</td>
      <td>BIO</td>
      <td>EF</td>
      <td>EF</td>
    </tr>
    <tr>
      <td>Directorate for Computer &amp; Information Science &amp; Engineering </td>
      <td>CISE</td>
      <td>OAD</td>
      <td>CISE,CCF,CNS,IIS</td>
    </tr>
    <tr>
      <td>Division of Computing and Communication Foundations</td>
      <td>CISE</td>
      <td>CCF</td>
      <td>CCF</td>
    </tr>
    <tr>
      <td>Division of Computer and Network Systems</td>
      <td>CISE</td>
      <td>CNS</td>
      <td>CNS</td>
    </tr>
    <tr>
      <td>Division of Information and Intelligent Systems</td>
      <td>CISE</td>
      <td>IIS</td>
      <td>IIS</td>
    </tr>
    <tr>
      <td>Directorate for Education &amp; Human Resources </td>
      <td>EHR</td>
      <td>OAD</td>
      <td>EHR,DRL,DGE,HRD,DUE</td>
    </tr>
    <tr>
      <td>Division of Research on Learning in Formal and Informal Settings</td>
      <td>EHR</td>
      <td>DRL</td>
      <td>DRL</td>
    </tr>
    <tr>
      <td>Division of Graduate Education</td>
      <td>EHR</td>
      <td>DGE</td>
      <td>DGE</td>
    </tr>
    <tr>
      <td>Division of Human Resource Development</td>
      <td>EHR</td>
      <td>HRD</td>
      <td>HRD</td>
    </tr>
    <tr>
      <td>Division of Undergraduate Education</td>
      <td>EHR</td>
      <td>DUE</td>
      <td>DUE</td>
    </tr>
    <tr>
      <td>Directorate for Engineering </td>
      <td>ENG</td>
      <td>OAD</td>
      <td>ENG,CBET,CMMI,ECCS,EEC,EFRI,IIP</td>
    </tr>
    <tr>
      <td valign="bottom">
        <p>Division of Chemical, Bioengineering, Environmental, and   </p>
        <p>Transport Systems</p>
      </td>
      <td>ENG</td>
      <td>CBET</td>
      <td>CBET</td>
    </tr>
    <tr>
      <td>Division of Civil, Mechanical &amp; Manufacturing Innovation</td>
      <td>ENG</td>
      <td>CMMI</td>
      <td>CMMI</td>
    </tr>
    <tr>
      <td>Division of Electrical, Communications &amp; Cyber Systems</td>
      <td>ENG</td>
      <td>ECCS</td>
      <td>ECCS</td>
    </tr>
    <tr>
      <td>Division of Engineering Education &amp; Centers</td>
      <td>ENG</td>
      <td>EEC</td>
      <td>EEC</td>
    </tr>
    <tr>
      <td>Office of Emerging Frontiers in Research &amp; Innovation</td>
      <td>ENG</td>
      <td>EFRI</td>
      <td>EFRI</td>
    </tr>
    <tr>
      <td>Division of Industrial Innovation &amp; Partnerships</td>
      <td>ENG</td>
      <td>IIP</td>
      <td>IIP</td>
    </tr>
    <tr>
      <td>Directorate for Geosciences </td>
      <td>GEO</td>
      <td>OAD</td>
      <td>GEO,AGS,EAR,OCE</td>
    </tr>
    <tr>
      <td>Division of Atmospheric and Geospace Sciences</td>
      <td>GEO</td>
      <td>AGS</td>
      <td>AGS</td>
    </tr>
    <tr>
      <td>Division of Earth Sciences</td>
      <td>GEO</td>
      <td>EAR</td>
      <td>EAR</td>
    </tr>
    <tr>
      <td>Division of Ocean Sciences</td>
      <td>GEO</td>
      <td>OCE</td>
      <td>OCE</td>
    </tr>
    <tr>
      <td>Directorate for Mathematical &amp; Physical Sciences </td>
      <td>MPS</td>
      <td>OAD</td>
      <td>MPS,AST,CHE,DMR,DMS,PHY</td>
    </tr>
    <tr>
      <td>Division of Astronomical Sciences</td>
      <td>MPS</td>
      <td>AST</td>
      <td>AST</td>
    </tr>
    <tr>
      <td>Division of Chemistry</td>
      <td>MPS</td>
      <td>CHE</td>
      <td>CHE</td>
    </tr>
    <tr>
      <td>Division of Materials Research</td>
      <td>MPS</td>
      <td>DMR</td>
      <td>DMR</td>
    </tr>
    <tr>
      <td>Division of Mathematical Sciences</td>
      <td>MPS</td>
      <td>DMS</td>
      <td>DMS</td>
    </tr>
    <tr>
      <td>Division of Physics</td>
      <td>MPS</td>
      <td>PHY</td>
      <td>PHY</td>
    </tr>
    <tr>
      <td>Directorate for Social, Behavioral &amp; Economic Sciences </td>
      <td>SBE</td>
      <td>OAD</td>
      <td>SBE,SES,BCS,NCSE,SMA</td>
    </tr>
    <tr>
      <td>Division of Social and Economic Sciences</td>
      <td>SBE</td>
      <td>SES</td>
      <td>SES</td>
    </tr>
    <tr>
      <td>Division of Behavioral and Cognitive Sciences</td>
      <td>SBE</td>
      <td>BCS</td>
      <td>BCS</td>
    </tr>
    <tr>
      <td>National Center for Science and Engineering Statistics</td>
      <td>SBE</td>
      <td>NCSE</td>
      <td>NCSE</td>
    </tr>
    <tr>
      <td>SBE Office of Multidisciplinary Activities</td>
      <td>SBE</td>
      <td>SMA</td>
      <td>SMA</td>
    </tr>
    <tr>
      <td>Office of Budget, Finance, and Award Management</td>
      <td>BFA</td>
      <td>OAD</td>
      <td>BFA,BD,DACS,DFM,DGA,DIAS</td>
    </tr>
    <tr>
      <td>Budget Division</td>
      <td>BFA</td>
      <td>BD</td>
      <td>BD</td>
    </tr>
    <tr>
      <td>Division of Acquisition and Cooperative Support</td>
      <td>BFA</td>
      <td>DACS</td>
      <td>DACS</td>
    </tr>
    <tr>
      <td>Division of Financial Management</td>
      <td>BFA</td>
      <td>DFM</td>
      <td>DFM</td>
    </tr>
    <tr>
      <td>Division of Grants &amp; Agreements</td>
      <td>BFA</td>
      <td>DGA</td>
      <td>DGA</td>
    </tr>
    <tr>
      <td>Division of Institution and Award Support</td>
      <td>BFA</td>
      <td>DIAS</td>
      <td>DIAS</td>
    </tr>
    <tr>
      <td>Office of Information &amp; Resource Management </td>
      <td>OIRM</td>
      <td>OAD</td>
      <td>OIRM,HRM,DIS,DAS</td>
    </tr>
    <tr>
      <td>Division of Human Resource Management</td>
      <td>OIRM</td>
      <td>HRM</td>
      <td>HRM</td>
    </tr>
    <tr>
      <td>Division of Information Systems</td>
      <td>OIRM</td>
      <td>DIS</td>
      <td>DIS</td>
    </tr>
    <tr>
      <td>Division of Administrative Services</td>
      <td>OIRM</td>
      <td>DAS</td>
      <td>DAS</td>
    </tr>
  </tbody>
</table>

app/views/pages/sdk.html.erb
<div id="header" class="page-header">
    <h2>JavaScript SDK</h1>
	<p class="lead">A software development kit to include in your JavaScript projects.</p>
</div>
<div class="section">
<h2>How To Use</h2>
<p><a href="js/libs/sm.js" target="_blank">Download the script file</a> and place it in your project directory.</p>
<p>Include it in your project as follows:</p>
<code>&lt;script src="pathtofile/sm.js" type="text/javascript" /&gt;</code>
</div>
<div class="section">
<h2>StarMetrics JavaScript SDK Usage</h2>
<form class="well form-horizontal">
	<div class="control-group">
		<label class="control-label"><strong>Show:</strong></label>
		<div class="controls">
			<select id="resource">
				<option value="">Select One</option>
				<option value="topics">List of Topics</option>
				<option value="programs">List of Programs</option>
				<option value="divisions">List of Divisions</option>
				<option value="proposals">List of Proposals</option>
				<option value="institutions">List of Institutions</option>
				<option value="researchers">List of Researchers</option>
				<option value="">----</option>
				<option value="proposal">Proposal Details</option>
				<option value="institution">Institution Details</option>
				<option value="researcher">Researcher Details</option>
			</select>
		    <p class="help-block">Select an option above. The SDK call and the call results will be displayed below.</p>
		</div>
       </div>
</form>
<h2>Call</h2>
<pre id="call"></pre>
<h2>Result</h2>
<pre id="result"></pre>
</div>

<script type="text/javascript">
LoadView = Backbone.View.extend({
	events: {
		"change select#resource": "load",
	},
	load: function(e) {
		if (e) e.preventDefault();
		$('#result', this.el).html('Loading...');
		var resource = $('#resource').val();
		var options;
		if (resource=='topics') {
			options = {org:'CMMI',year:'2007-2009'};
			StarMetrics.topics(options,this.render);
		} else if (resource=='programs') {
			options = {org:'CMMI',year:'2007-2009'};
			StarMetrics.programs(options,this.render);						
		} else if (resource=='divisions') {
			options = {t:'551',year:'2007-2009'};
			StarMetrics.divisions(options,this.render);
		} else if (resource=='proposals') {
			options = {org:'CMMI',year:'2007-2009'};
			StarMetrics.proposals(options,this.render);						
		} else if (resource=='institutions') {
			options = {org:'CMMI',year:'2007-2009'};
			StarMetrics.institutions(options,this.render);						
		} else if (resource=='researchers') {
			options = {org:'CMMI',year:'2007-2009'};
			StarMetrics.researchers(options,this.render);						
		} else if (resource=='proposal') {
			options = '1126899';
			StarMetrics.proposal(options,this.render);						
		} else if (resource=='institution') {
			options = '0038950000';
			StarMetrics.institution(options,this.render);						
		} else if (resource=='researcher') {
			options = '269729592';
			StarMetrics.researcher(options,this.render);
		}
		if (typeof(options)!=='string') options = JSON.stringify(options);
		$('#call', this.el).html("StarMetrics."+resource+"("+options+",callback);");		
	},
	render: function(result) {
		if (result) result = jsl.format.formatJson(JSON.stringify(result));
		else result = '<div class="alert"><strong>Error</strong>: You must be connected to the NSF network to access the API.</div>';
		$('#result', this.el).html(result);
	}	
});
$(function(){
	var view = new LoadView({el:$('#main')});
});
</script>